FROM nginx:1.15.0-alpine

#Aqui estou removendo as configuracoes padrao do nginx
RUN rm /etc/nginx/conf.d/default.conf 

#Aqui estou adicionando as minhas configuracoes
COPY ./nginx.conf /etc/nginx/conf.d

#RUN apt-get update

# Esse processo interessante quando colocar no servidor em on-line, ele faz tudo automatizado para mim. 
#RUN apt-get update && \
    #apt-get install -y software-properties-common && \   
    #add-apt-repository universe && \   
    #add-apt-repository ppa:certbot/certbot && \
    #apt-get update && \
    #apt-get install -y certbot && \
    #apt-get install -y python-certbot-nginx && \     
    #apt-get install -y ufw && \   
    #certbot --nginx -d example.com -d www.example.com
    #certbot certonly --nginx
    #certbot renew --dry-run